blocks-per-second: 5000
nukes:
  - fuse: 15
    incendiary: false
    name: '&cNuclear warhead'
    recipe:
      - Steel_Plate
      - Boosted_Uranium
      - Steel_Plate
      - Piston
      - Boosted_Uranium
      - Piston
      - Steel_Plate
      - Boosted_Uranium
      - Steel_Plate
    id: LITTLE_NUKE
    radius: 32
  - fuse: 30
    incendiary: true
    name: '&cThermonuclear warhead'
    recipe:
      - Steel_Plate
      - Boosted_Uranium
      - Steel_Plate
      - Piston
      - Boosted_Uranium
      - Piston
      - Steel_Plate
      - Boosted_Uranium
      - Steel_Plate
    id: MEDIUM_NUKE
    radius: 32
  - fuse: 45
    incendiary: false
    name: '&cHydrong bomb'
    recipe:
      - Steel_Plate
      - Ongium
      - Steel_Plate
      - Piston
      - Ongium
      - Piston
      - Steel_Plate
      - Ongium
      - Steel_Plate
    id: Ong_NUKE
    radius: 32
research-cost: 50